api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt import views as jwt_views
from .views import *

router = routers.DefaultRouter()
router.register(r"utilisateurs", UtilisateurViewSet)
router.register(r"fournisseurs", StationViewSet)
router.register(r"stations", StationViewSet)
router.register(r"pompes", StationViewSet)
router.register(r"types-carburants", StationViewSet)
router.register(r"reservoirs", StationViewSet)
router.register(r"index", StationViewSet)
router.register(r"commandes", StationViewSet)
router.register(r"lignes-commandes", StationViewSet)


urlpatterns = [
    path('token/obtain/', jwt_views.TokenObtainPairView.as_view(), name='token_create'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('blacklist/', LogoutAndBlacklistRefreshTokenForUserView.as_view(), name="blacklist"),

    path('', include(router.urls)),
    path('current-user/', current_user, name='current_user')
]

frontend/urls.py
from django.urls import path, include

from . import views

app_name = 'fuel'

urlpatterns = [
    path('', views.HomeView.as_view()),
    path('home/', views.HomeView.as_view(), name="home"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('settings/', include([
        path('station/', views.setting_station_view, name="setting_station"),
        path('fournisseurs/', views.setting_fournisseurs_view, name="setting_fournisseurs"),
        path('reservoirs/', views.setting_reservoirs_view, name="setting_reservoirs"),
    ]))
]

web/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/stataic/img/logo/favicon.png')),
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('', include("frontend.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from api import models

# Create your views here.


class LoginView(generic.TemplateView):
    template_name = "pages/login.html"
    error = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["error"] = self.error
        return context

    def post(self, request, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            return redirect("fuel:home")
        self.error = True
        return self.get(request, **kwargs)


class LogoutView(generic.View):
    @staticmethod
    def get(request, **kwargs):
        logout(request)
        return redirect("fuel:login")


@method_decorator(login_required, name="dispatch")
class HomeView(generic.TemplateView):
    template_name = "pages/index.html"


@method_decorator(login_required, name="dispatch")
class ProfileView(generic.UpdateView):
    template_name = "pages/profile.html"
    fields = ['last_name', 'first_name', 'email', 'pays', 'nationalite', 'adresse', 'username']

    def get_object(self, queryset=None):
        return models.Utilisateur.objects.get(pk=self.request.user.pk)

    def get_success_url(self):
        password = self.request.POST["password"]
        user = self.get_object()
        if user.check_password(password):
            password = self.request.POST["new_password"]
            user.set_password(password)
            user.save()
            update_session_auth_hash(self.request, user)
        return reverse('fuel:profile')


@login_required
def setting_station_view(request):
    station = models.Station.objects.get(utilisateur__username=request.user.username)
    type_carburants = models.TypeCarburant.objects.filter(station=station)
    return render(request, "pages/settings/station.html", locals())


@login_required
def setting_fournisseurs_view(request):
    fournisseurs = models.Fournisseur.objects.filter(station__utilisateur__username=request.user.username)
    return render(request, "pages/settings/fournisseurs.html", locals())


@login_required
def setting_reservoirs_view(request):
    station = models.Station.objects.get(utilisateur__username=request.user.username)
    pompes = models.Pompe.objects.filter(station=station)
    indexs = models.Index.objects.filter(pompe__station=station)
    reservoirs = models.Reservoir.objects.filter(station=station)
    print(pompes, indexs, reservoirs)
    return render(request, "pages/settings/reservoirs.html")

frontend/templates/shared/_css.html
{% load static %}
<link rel="stylesheet" href="{% static 'fonts/material-design-icons/material-icons.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="{% static 'css/top_left.css' %}">
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
<link rel="stylesheet" href="{% static 'css/tabs.css' %}">
<link rel="stylesheet" href="{% static 'css/pagination.css' %}">

frontend/templates/shared/_js.html
{% load static %}
<script src="{% static 'js/main.js' %}"></script>

frontend/templates/shared/_left_bar.html
{% load static %}

<ul class="sidenav--header">
    <li class="sidenav-nav-link sidenav--menu sidenav--logo">
        <a href="{% url 'fuel:home' %}"><img src="{% static 'img/logo/favicon.png' %}" alt="logo"></a>
    </li>
    <li class="sidenav-nav-link sidenav--menu ">
        <a href="{% url 'fuel:home' %}" {% if selection|default:'home' == 'home' %} class="active"{% endif %}>
            <i class="material-icons">home</i>
        </a>
        <div class="sidenav--help">Accueil</div>
    </li>
    <li class="sidenav-nav-link sidenav--menu">
        <a href="#" {% if selection == 'stations' %} class="active"{% endif %}>
            <i class="material-icons">apps</i>
        </a>
        <div class="sidenav--help">Stations</div>
    </li>
    <li class="sidenav-nav-link sidenav--menu">
        <a href="#" {% if selection == 'users' %} class="active"{% endif %}>
            <i class="material-icons">people</i>
        </a>
        <div class="sidenav--help">Utilisateurs</div>
    </li>
    <li class="sidenav-nav-link sidenav--menu">
        <a href="#" {% if selection == 'messages' %} class="active"{% endif %}>
            <i class="material-icons">notifications</i>
        </a>
        <div class="sidenav--help">Messages</div>
    </li>
</ul>
<ul class="sidenav--footer">
    <li class="sidenav-nav-link sidenav--menu">
        <a href="{% url 'fuel:profile' %}" {% if selection == 'profile' %} class="active"{% endif %}>
            <i class="material-icons">account_circle</i>
        </a>
        <div class="sidenav--help">Profile</div>
    </li>
    <li class="sidenav-nav-link sidenav--menu ">
        <a href="{% url 'fuel:setting_station' %}" {% if selection == 'setting' %}class="active"{% endif %}>
            <i class="material-icons">settings</i>
        </a>
        <div class="sidenav--help">Paramètres</div>
    </li>
    <li class="sidenav-nav-link sidenav--menu">
        <a href="{% url 'fuel:logout' %}"><i class="material-icons">power_settings_new</i></a>
        <div class="sidenav--help">Déconnexion</div>
    </li>
</ul>

frontend/templates/shared/_pagination.html
<div class="pagination-wrapper">
    <ul class="pagination">
        <li class="page-prev"><a href="#"> < prev </a></li>
        <li class="page-num"><a href="#">1</a></li>
        <li class="page-num active"><a href="#">2</a></li>
        <li class="page-num"><a href="#">3</a></li>
        <li class="page-num"><a href="#">4</a></li>
        <li class="page-num"><a href="#">5</a></li>
        <li class="page-num"><a href="#">6</a></li>
        <li class="page-next"><a href="#"> next > </a></li>
    </ul>
</div>

frontend/templates/shared/_tabs.html
<div class="tabs-header">
    <a href="{% url 'fuel:setting_station' %}" {% if selection|default:'station' == 'station' %}class="active"{% endif %}>Station</a>
    <a href="{% url 'fuel:setting_fournisseurs' %}" {% if selection == 'fournisseurs' %}class="active"{% endif %}>Fournisseurs</a>
    <a href="{% url 'fuel:setting_reservoirs' %}" {% if selection == 'reservoirs' %}class="active"{% endif %}>Reservoirs</a>
</div>